#!/usr/bin/env perl
use strict;
use warnings;

use Log::Log4perl qw(get_logger :no_extra_logdie_message);
use Data::Dumper;

# Reads a list of trace files generated by smpirun.sh and read the
# communication done by each CPU. In the end, prints the communication matrix.

my ($trace_file_name, $cpus_number) = @ARGV;

my @comm = map { [(0) x $cpus_number] } (0..($cpus_number - 1));

open(my $trace_file, '<', $trace_file_name) or die ('unable to open main trace file');

while (my $trace_line = <$trace_file>) {
	chomp $trace_line;

	next unless ($trace_line =~ /^15 \d*\.\d* \d* \d* PTP \d* (\d*)_(\d*)/);
	my $source = $1;
	my $dst = $2;

	$comm[$source]->[$dst]++;
}

print join(' ', @{$_}) . "\n" for (@comm);
