#!/usr/bin/env perl
use strict;
use warnings;

use Log::Log4perl qw(get_logger :no_extra_logdie_message);
use Data::Dumper;

# Reads a list of trace files generated by smpirun.sh and read the
# communication done by each CPU. In the end, prints the communication matrix.

my ($main_trace_file_name, $cpus_number) = @ARGV;

open(my $main_trace_file, '<', $main_trace_file_name) or die ('unable to open main trace file');

while (my $main_trace_line = <$main_trace_file>) {
	chomp $main_trace_line;
	print read_trace_file($main_trace_line) . "\n";
}

sub read_trace_file {
	my $file_name = shift;

	my @sends = (0) x $cpus_number;

	open(my $file, '<', $file_name) or die ("unable to open file $file_name");

	while (my $line = <$file>) {
		chomp $line;
		my @line_parts = split(' ', $line);

		if ($line_parts[1] eq 'send') {
			$sends[$line_parts[2]]++;
		}
	}

	close($file);
	return join(' ', @sends);
}

sub benchmark_name {
	my $file_name = shift;

	my $base_name = `basename $file_name .trace`;
	my @base_name_parts = split('-', $base_name);
	return $base_name_parts[0];
}

